<%@ Page Language="C#" MasterPageFile="~/masterMain.master" AutoEventWireup="true" CodeFile="ResourceLinks.aspx.cs" Inherits="ResourceLinks" Title="District One Links" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div class="container">
        <div class="row" style="background-color:lavender">
            <div class="col-sm-12 text-sm-center">
                    <span style="font-size: 24px; color: #FF0000">New Jersey District 1 Little League
                    </span>
                    <br />
                    <span style="font-size: 18px; color: #000066; font-family: Calibri">District Administrator - Chris Graham
                    </span><br />
            <span style="font-size: 18px; color: #000066; font-family: Calibri"> NJ District One Resources</span><br />
            </div>
        </div>
    </div>
    <br />
    <div class="container">
        <div class="row border border-dark bg-dark text-white p-2">
            <div class="col-sm-6 text-center">
                <span class="col-form-label-lg text-primary">Local Links</span>
                <asp:TreeView CssClass="text-center" ID="tvLocal" runat="server">
                    <Nodes>
                        <asp:TreeNode NavigateUrl="http://www.eteamz.active.com/llbeast/index.cfm?" Target="_blank"
                            Text="Little League East Region" Value="Little League East Region"></asp:TreeNode>
                        <asp:TreeNode NavigateUrl="http://www.eteamz.active.com/njstatell/index.cfm?" Target="_blank"
                            Text="New Jersey State Little League" Value="New Jersey State Little League"></asp:TreeNode>
                    </Nodes>
                </asp:TreeView>
            </div>
            <div class="col-sm-6 text-center">
                <span class="col-form-label-lg text-primary">Little League Links</span>
                <asp:TreeView CssClass="text-center" ID="tvLL" runat="server" AutoGenerateDataBindings="False">
                    <Nodes>
                        <asp:TreeNode NavigateUrl="http://www.littleleague.org" Target="_blank" Text="Little League International"
                            Value="Little League International">
                            <asp:TreeNode NavigateUrl="http://www.littleleague.org/learn/rules.htm" Target="_blank"
                                Text="Little League Rules" Value="Little League Rules"></asp:TreeNode>
                            <asp:TreeNode NavigateUrl="http://www.littleleague.org/learn/forms.htm" Target="_blank"
                                Text="Little League Forms" Value="Little League Forms"></asp:TreeNode>
                            <asp:TreeNode NavigateUrl="http://www.littleleague.org/districtadmins/safetyplanstatus/Safety_Plan_Status.htm"
                                Text="ASAP Plan Status" Value="ASAP Plan Status"></asp:TreeNode>
                            <asp:TreeNode NavigateUrl="http://www.littleleague.org/learn/equipment/equipment-merchandise.htm"
                                Target="_blank" Text="Approved Equipment Lists" Value="Approved Equipment Lists"></asp:TreeNode>
                        </asp:TreeNode>
                        <asp:TreeNode NavigateUrl="http://www.eteamz.active.com/llwsuai" Target="_blank"
                            Text="World Series Umpires Alumni Association" Value="World Series Umpires Alumni Association"></asp:TreeNode>
                    </Nodes>
                </asp:TreeView>
            </div>
        </div>
    </div>
</asp:Content>

